name: CI/CD for Flask App with Docker

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests (optional)
      run: |
        pytest || echo "No tests found - skipping"

    - name: Deploy to VPS with Docker
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          cd /www/wwwroot/inhouse_project/

          if [ ! -d ".git" ]; then
            echo "Cloning repository into current directory..."
            git clone https://github.com/arvitai4135/conversation-bot.git .
          else
            echo "Pulling latest changes..."
            git pull origin main
          fi

          echo "${{ secrets.ENV_CONTENT }}" > .env

          echo "Building Docker image..."
          docker build -t flask-conversation-bot .

          echo "Stopping and removing old container..."
          docker stop flask-bot || true
          docker rm flask-bot || true

          echo "Starting new Docker container..."
          docker run -d \
            --name flask-bot \
            -p 5051:5051 \
            --env-file .env \
            flask-conversation-bot
